name: Sync canboat.json

on:
  schedule:
    - cron: '0 3 * * 1'  # Runs at 03:00 UTC every Monday
  workflow_dispatch:  # Allows manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Don't use default GitHub credentials

      - name: Fetch latest file from source repo
        run: |
          curl -o canboat.json.new https://raw.githubusercontent.com/canboat/canboat/refs/heads/master/docs/canboat.json

      - name: Check for changes
        run: |
          if cmp -s canboat.json canboat.json.new; then
            echo "No changes detected."
            exit 0
          fi
          echo "canboat.json changed, proceeding with PR creation."
          mv canboat.json.new canboat.json

      - name: Compile CANBoat to Python
        run: python3 canboat2python.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: update-synced-file
          delete-branch: true
          title: "Sync canboat.json"
          body: "This PR updates `canboat.json` from `canboat` repo."
          commit-message: "Update canboat.json from source repo"
          base: main
          labels: "automation"
